server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: hypermarketapi
  datasource:
    url: jdbc:h2:mem://localhost:8082/hypermarketapi
    username: user
    password: p@ssw0rd
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    properties:
      hibernate:
        time_zone: UTC
        default_schema: hypermarketapi
        ddl-auto: validate

management:
  server:
    port: 9090
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    db:
      enabled: true
  endpoints.web.exposure.include: "*"